# Generated by Django 4.2 on 2023-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_auth',
            field=models.BooleanField(default=False),
        ),
    ]
