# Generated by Django 4.2 on 2023-04-21 15:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_site_description_alter_site_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='day',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='description',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='itinerary',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='no_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='localdelicacy',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=200),
        ),
    ]
