# Generated by Django 4.2 on 2023-05-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_hotel_booking_url_alter_hotel_hotel_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TravelPreference',
        ),
        migrations.AddField(
            model_name='traveloption',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip'),
        ),
    ]
