# Generated by Django 4.2 on 2023-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_dietery_preference_trip_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
