# Generated by Django 4.2 on 2023-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_remove_itinerary_day_remove_itinerary_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
