# Generated by Django 4.2 on 2023-05-15 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_traveloption_trip_is_save_delete_travelpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='localdelicacy',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_delicacy', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='site',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='traveloption',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_option', to='trip.trip'),
        ),
    ]
