# Generated by Django 4.2 on 2023-04-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_site_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='location',
            new_name='location_id',
        ),
    ]
