# Generated by Django 4.2 on 2023-05-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_itinerary_trip_alter_localdelicacy_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='traveloption',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_options', to='trip.trip'),
        ),
    ]
