# Generated by Django 4.2 on 2023-04-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_rename_location_site_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='location_id',
            new_name='place_id',
        ),
    ]
