# Generated by Django 4.2 on 2023-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_rename_location_id_site_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
