# Generated by Django 4.2 on 2023-04-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_trip_destination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
